name: mobile_erp
description: A comprehensive mobile ERP solution built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # HTTP & Networking
  http: ^1.1.0
  connectivity_plus: ^4.0.2

  # Local Storage
  shared_preferences: ^2.2.2

  # File Operations
  path_provider: ^2.1.1
  file_picker: ^8.3.6

  # Excel & CSV
  excel: ^4.0.2
  csv: ^5.0.2

  # Notifications
  share_plus: ^10.0.0
  timezone: ^0.9.2

  # UI Components
  cupertino_icons: ^1.0.2

  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0

  # Charts
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true